api-prefix: /api/v1
server:
  port: 10000

spring:
  application:
    name: Car Transaction
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ctm-spring
            client-secret: ElPgPVMYg9chploJ2NGaye2drh7v9gMb
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/car-transaction-management
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/car-transaction-management/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/ctm
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true